# Generated by Django 4.1.1 on 2022-10-01 11:38

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=product.models.upload_to)),
            ],
        ),
    ]
